#!/usr/bin/env bash
# Usage: ./0-world_wide_web <domain> <subdomain>
# Display information about subdomains.

domain_info () {
    dig "$1" | grep -A1 'ANSWER SECTION:' | sed -r "s/$1./$2/g" | awk -F" " ' NR==2 {print "The subdomain " $1 " is a " $4 " record and points to " $5}'
}

if [ "$#" == 1 ]
then
  domain_info "$1" "www"
  domain_info "$1" "lb-01"
  domain_info "$1" "web-01"
  domain_info "$1" "web-02"
elif [ "$#" == 2 ]
then
  domain_information "$1" "$2"
fi
