#!/usr/bin/env bash
# Display information about subdomains.

domain_info () {
    dig "$1" | grep -A1 'ANSWER SECTION:' | sed -r "s/$1./$2/g" | awk -F" " ' NR==2 {print "The subdomain " $1 " is a " $4 " record and points to " $5}'
}

if [ "$#" == 1 ]
then
  domain_info "www.$1" "www"
  domain_info "lb-01.$1" "lb-01"
  domain_info "web-01.$1" "web-01"
  domain_info "web-02.$1" "web-02"
elif [ "$#" == 2 ]
then
  domain_info "$2.$1" "$2"
fi
