#!/usr/bin/env bash
# Configures a new ubuntu machine by installing Nginx on port 80
# Serve a page that would return a Hello World string

sudo apt update
sudo apt install nginx -y
sudo service nginx start
sudo ufw allow 'Nginx HTTP'
sudo ufw allow 80
sudo chown -R $USER:$USER /var/www/html/index.nginx-debian.html
sudo echo "Hello World!" > /var/www/html/index.nginx-debian.html
