#!/usr/bin/env bash
# Code displays numbers from 1 to 100

for ((c = 1; c <= 100; c++));
	do
	if ((c % 5 == 0)) && ((c % 3 == 0));
		then
		echo "FizzBuzz";
	elif ((c % 3 == 0));
		then
		echo "Fizz";
	elif ((c % 5 == 0));
		then
		echo "Buzz";
	else
		echo $c;
	fi;
done;
