#!/usr/bin/env bash
#Code displays numbers from 1 to 20.

C = 1
while [ $C -lt 21 ]
do
    case $C in

        4)
	    echo $C
	    echo "bad luck from China"
	    ;;
	
	9)
	    echo $C
	    echo "bad luck from Japan"
	    ;;
	
	17)
	    echo $C
	    echo "bad luck from Italy"
	    ;;

	*)
	    echo $C
	    ;;
    esac

          ((C++))
    done
